# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageDialog(object):
    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImageDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton = QtWidgets.QPushButton(ImageDialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(ImageDialog)
        self.radioButton.setGeometry(QtCore.QRect(90, 100, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(ImageDialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(60, 140, 222, 48))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.lineEdit = QtWidgets.QLineEdit(ImageDialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 130, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(ImageDialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(260, 20, 104, 87))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.dateEdit = QtWidgets.QDateEdit(ImageDialog)
        self.dateEdit.setGeometry(QtCore.QRect(40, 200, 110, 22))
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(ImageDialog)
        self.buttonBox.accepted.connect(ImageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Dialog"))
        self.pushButton.setText(_translate("ImageDialog", "PushButton"))
        self.radioButton.setText(_translate("ImageDialog", "RadioButton"))
        self.commandLinkButton.setText(_translate("ImageDialog", "CommandLinkButton"))
